version: 2.1

executors:
  app:
    working_directory: ~/src

    docker:
      - image: telusops/build-essential:latest

commands:
  persist:
    steps:
      - persist_to_workspace: { root: ~/src, paths: . }

  attach:
    steps:
      - attach_workspace: { at: "." }

jobs:
  build:
    executor: app
    steps:
      - checkout
      - persist

  audit:
    executor: app
    steps:
      - attach
      - run: npm audit

  lint:
    executor: app
    steps:
      - attach
      - run: npm run lint

  release:
    executor: app
    steps:
      - attach
      - run: npx semantic-release

workflows:
  version: 2
  run:
    jobs:
      - build:
          context: npm-library

      - lint:
          requires: [ build ]

      - audit:
          requires: [ build ]

      - release:
          context: npm-library
          requires: [ build, audit, lint ]
          filters:
            branches:
              only: master
